//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonasPerdidas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrearPersonaPerdida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrearPersonaPerdida()
        {
            this.FotosPersona = new HashSet<FotosPersona>();
        }
    
        public int Id_CPP { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha_desaparicion { get; set; }
        public int Edad { get; set; }
        public int Pariente { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> FechaEncontrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosPersona> FotosPersona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
